# Generated by Django 3.2 on 2021-04-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_modify_authors', 'Can add, delete and change authors'),)},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Can mark book as returned'), ('can_renew', 'Can mark book as renewed'))},
        ),
    ]
